version: "3.8"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      DBUsername: go_assessment_user
      DBPassword: KaCT3XW2UKgE
      DBName: go_assessment_db
      DBHost: database
      DBPort: 5432
      RedisHost: redis
      RedisPort: 6379
      JWTSecret: dxiyXWAcMnj66j3y4JPC7HhwUiW6CFqQecL7dpYU4qmbtj
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: go_assessment_user
      POSTGRES_PASSWORD: KaCT3XW2UKgE
      POSTGRES_DB: go_assessment_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - app-network

  migrate:
    image: migrate/migrate
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://go_assessment_user:KaCT3XW2UKgE@db:5432/go_assessment_db?sslmode=disable",
        "up",
      ]
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
