version: "3.8"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      DB_USERNAME: go_assessment_user
      DB_PASSWORD: KaCT3XW2UKgE
      DB_NAME: go_assessment_db
      DB_HOST: localhost
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: dxiyXWAcMnj66j3y4JPC7HhwUiW6CFqQecL7dpYU4qmbtj

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: go_assessment_user
      POSTGRES_PASSWORD: KaCT3XW2UKgE
      POSTGRES_DB: go_assessment_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres_data:
